#!/bin/bash

# Maven
#mvn exec:java -Dexec.mainClass="org.redhat.amq.tools.ProducerEventTool" -Dexec.args="$*"   

# Pure Java using uber jar
java -cp ./target/uber-amq-tools.jar org.redhat.amq.tools.ProducerEventTool $*
