#!/bin/bash

#
# Runs the Producer Tool
#
export CLASSPATH=.:$CLASSPATH

# Maven
#mvn exec:java -Dexec.mainClass="org.redhat.amq.tools.ProducerTool" -Dexec.args="$*"   

# Pure Java using uber jar
java -cp ./target/uber-amq-tools.jar org.redhat.amq.tools.ProducerTool $*
